
random_id
Function to generate iids

#### Description 

Function to generate iids
Usage
random_id(n = 1, length = 10)
 #### Arguments 

n Number of ids
length Length of ids74
stars
renderHighchart
Widget render function for use in Shiny

#### Description 

Widget render function for use in Shiny
Usage
renderHighchart(expr, env = parent.frame(), quoted = FALSE)
renderHighchart2(expr, env = parent.frame(), quoted = FALSE)
 #### Arguments 

expr A highchart expression.
env A enviorment.
quoted A boolean value.

String to ’id’ format

#### Description 

Turn a string to id format used in treemaps.
Usage
str_to_id(x)
 #### Arguments 

x
A vector string.
Examples
str_to_id(" A string _ with sd / sdg
tooltip_table
Underscores \
")
Helper for make table in tooltips

#### Description 

Helper to make table in tooltips for the pointFormat parameter in hc_tooltip
Usage
tooltip_table(x, y, title = NULL, img = NULL, ...)
 #### Arguments 

x A string vector with 
#### Description 
 text
y A string with accesors ex: point.series.name, point.x
title A title tag with accessor or string
img Img tag
... html attributes for the table element76
unemployment
Examples
x <- c("Income:", "Genre", "Runtime")
y <- c("$ {point.y}", "{point.series.options.extra.genre}",
"{point.series.options.extra.runtime}")
tooltip_table(x, y)



uscountygeojson
77
US Counties map in Geojson format (list)

#### Description 

This data comes from the https://code.highcharts.com/mapdata/countries/us/us-all-all.
js and is used in highmaps examples.
Usage
uscountygeojson
#### Format

A list in geojson format.
usgeojson
US States map in Geojson format (list)

#### Description 

This data comes from the https://code.highcharts.com/mapdata/countries/us/us-all.js
and is used in highmaps examples.
Usage
usgeojson
#### Format

A list in geojson format.
