
hc_theme_darkunica
Dark Unica theme for highcharts

#### Description 

Dark Unica theme for highcharts
Usage
hc_theme_darkunica(...)
 #### Arguments 

...
Named argument to modify the theme
Examples
highcharts_demo() %>%
hc_add_theme(hc_theme_darkunica())
hc_theme_db
Dotabuff theme for highcharts

#### Description 

Dotabuff theme for highcharts
Usage
hc_theme_db(...)
 #### Arguments 

...
Named argument to modify the theme
Examples
highcharts_demo() %>%
hc_add_theme(hc_theme_db())56
hc_theme_elementary
hc_theme_economist
Economist theme for highcharts

#### Description 

Economist theme for highcharts
Usage
hc_theme_economist(...)
 #### Arguments 

...
Named argument to modify the theme
Examples
highcharts_demo() %>%
hc_add_theme(hc_theme_economist())
hc_theme_elementary
Elementary (OS) theme for highcharts

#### Description 

Elementary (OS) theme for highcharts based on https://elementary.io
Usage
hc_theme_elementary(...)
 #### Arguments 

...
Named argument to modify the theme
Examples
highcharts_demo() %>%
hc_add_theme(hc_theme_elementary())hc_theme_ffx
57
hc_theme_ffx
Firefox theme for highcharts

#### Description 

Theme inspired by https://www.mozilla.org/en-US/styleguide/
Usage
hc_theme_ffx(...)
 #### Arguments 

...
Named argument to modify the theme
Examples
highcharts_demo() %>%
hc_add_theme(hc_theme_ffx())
hc_theme_flat
Flat theme for highcharts

#### Description 

Base16 Insipred theme https://github.com/chriskempson/base16 and https://github.com/cttobin/ggthemr#flat
Usage
hc_theme_flat(...)
 #### Arguments 

...
Named argument to modify the theme
Examples
highcharts_demo() %>%
hc_add_theme(hc_theme_flat())58
hc_theme_ft
