---
title: "Ref_11.Rmd"
author: "Kevin O'Brien"
date: "12 October 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


hc_colors
Adding color options to highchart objects

#### Description 

An array containing the default colors for the chart’s series. When all colors are used, new colors
are pulled from the start again.
Usage
hc_colors(hc, colors)
 #### Arguments 

* ``hc ``: A highchart htmlwidget object.
colors A vector of colors.42
hc_credits
Examples
library("viridisLite")
cols <- viridis(3)
cols <- substr(cols, 0, 7)
highcharts_demo() %>%
hc_colors(cols)
hc_credits
Adding credits options to highchart objects

#### Description 

highcarter by default don’t put credits in the chart. You can add credits using these options.
Usage
hc_credits(hc, ...)
 #### Arguments 

* ``hc ``: A highchart htmlwidget object.
* ``...``: Arguments defined in http://api.highcharts.com/highcharts#credits.
Examples
data("citytemp")
highchart() %>%
hc_xAxis(categories = citytemp$month) %>%
hc_add_series(name = "Tokyo", data = citytemp$tokyo, type = "bar") %>%
hc_credits(enabled = TRUE, text = "htmlwidgets.org",
href = "http://www.htmlwidgets.org/")hc_defs
43
hc_defs
Adding patterns to be used in highcharts series

#### Description 

Helper function to use the fill patter plugin http://www.highcharts.com/plugin-registry/single/9/Pattern-
Fill.
Usage
hc_defs(hc, ...)
 #### Arguments 

* ``hc ``: A highchart htmlwidget object.
* ``...``: Arguments defined in http://www.highcharts.com/plugin-registry/single/
9/Pattern-Fill.
hc_drilldown
Drilldown options for higcharts objects

#### Description 

Options for drill down, the concept of inspecting increasingly high resolution data through clicking
on chart items like columns or pie slices.
Usage
hc_drilldown(hc, ...)
 #### Arguments 

* ``hc ``: A highchart htmlwidget object.
* ``...``: Arguments defined in http://api.highcharts.com/highcharts#drilldown.
Examples
library("dplyr")
library("purrr")
df <- data_frame(
name = c("Animals", "Fruits", "Cars"),
y = c(5, 2, 4),
drilldown = tolower(name)
)44
hc_drilldown
df
ds <- list_parse(df)
names(ds) <- NULL
str(ds)
hc <- highchart() %>%
hc_chart(type = "column") %>%
hc_title(text = "Basic drilldown") %>%
hc_xAxis(type = "category") %>%
hc_legend(enabled = FALSE) %>%
hc_plotOptions(
series = list(
boderWidth = 0,
dataLabels = list(enabled = TRUE)
)
) %>%
hc_add_series(
name = "Things",
colorByPoint = TRUE,
data = ds
)
dfan <- data_frame(
name = c("Cats", "Dogs", "Cows", "Sheep", "Pigs"),
value = c(4, 3, 1, 2, 1)
)
dffru <- data_frame(
name = c("Apple", "Organes"),
value = c(4, 2)
)
dfcar <- data_frame(
name = c("Toyota", "Opel", "Volkswage"),
value = c(4, 2, 2)
)
second_el_to_numeric <- function(ls){
map(ls, function(x){
x[[2]] <- as.numeric(x[[2]])
x
})
}
dsan <- second_el_to_numeric(list_parse2(dfan))
dsfru <- second_el_to_numeric(list_parse2(dffru))
dscar <- second_el_to_numeric(list_parse2(dfcar))hc_elementId
45
hc <- hc %>%
hc_drilldown(
allowPointDrilldown = TRUE,
series = list(
list(
id = "animals",
data = dsan
),
list(
id = "fruits",
data = dsfru
),
list(
id = "cars",
data = dscar
)
)
)
hc
