



highcarter-exports
highcharter exported operators and S3 methods

#### Description 

The following functions are imported and then re-exported from the highcarter package to avoid
listing the magrittr as Depends of highcarters.68
highchart2
highchart
Create a Highcharts chart widget

#### Description 

This function creates a Highchart chart using htmlwidgets. The widget can be rendered on HTML
pages generated from R Markdown, Shiny, or other applications.
Usage
highchart(hc_opts = list(), theme = getOption("highcharter.theme"),
type = "chart", width = NULL, height = NULL, elementId = NULL)
 #### Arguments 

hc_opts
theme
type
width
height
elementId
highchart2
A list object containing options defined as http://api.highcharts.com/
highcharts.
A hc_theme class object
A character value to set if use Highchart, Highstock or Highmap. Options are
"chart", "stock" and "map".
A numeric input in pixels.
A numeric input in pixels.
Use an explicit element ID for the widget.
Create a Highcharts chart widget

#### Description 

This widgets don’t support options yet.
Usage
highchart2(hc_opts = list(), theme = NULL, width = NULL, height = NULL,
elementId = NULL, debug = FALSE)
 #### Arguments 

hc_opts
theme
width
height
elementId
debug
A list object containing options defined as http://api.highcharts.com/
highcharts.
A hc_theme class object
A numeric input in pixels.
A numeric input in pixels.
Use an explicit element ID for the widget.
A boolean value if you want to print in the browser console the parameters given
to highchart.highchartOutput
69
Details
This function creates a Highchart chart using htmlwidgets. The widget can be rendered on HTML
pages generated from R Markdown, Shiny, or other applications.
highchartOutput
Widget output function for use in Shiny

#### Description 

Widget output function for use in Shiny
Usage
highchartOutput(outputId, width = "100%", height = "400px")
highchartOutput2(outputId, width = "100%", height = "400px")
 #### Arguments 

outputId The name of the input.
width A numeric input in pixels.
height A numeric input in pixels.
highcharts_demo
Chart a demo for testing themes

#### Description 

Chart a demo for testing themes
Usage
highcharts_demo()
Examples
highcharts_demo()70
is.hexcolor
hw_grid
Lays out highchart widgets into a "grid", similar to grid.arrange
from gridExtra

#### Description 

Lays out highchart widgets into a "grid", similar to grid.arrange from gridExtra
Usage
hw_grid(..., ncol = NULL, rowheight = NULL)
 #### Arguments 

... either individual highchart objects or a mixture of individual highchart ob-
jects and lists of highchart objects.
ncol how many columns in the grid
rowheight Height in px.
is.hexcolor
Check if a string vector is in hexadecimal color format

#### Description 

Check if a string vector is in hexadecimal color format
Usage
is.hexcolor(x)
 #### Arguments 

x
A string vectors
Examples
x <- c("#f0f0f0", "#FFf", "#99990000", "#00FFFFFF")
is.hexcolor(x)is.highchart
is.highchart
71
Reports whether x is a highchart object

#### Description 

Reports whether x is a highchart object
Usage
is.highchart(x)
 #### Arguments 

x
list_parse
An object to test
Convert an object to list with identical structure

#### Description 

This functions are similiar to rlist::list.parse but this removes names.
Usage
list_parse(df)
list_parse2(df)
list.parse2(df)
list.parse3(df)
 #### Arguments 

df
A data frame to parse to list
Examples
x <- data.frame(a=1:3, type=c('A','C','B'), stringsAsFactors = FALSE)
list_parse(x)
list_parse2(x)72
pokemon
mutate_mapping
Modify data frame accoring to mapping

#### Description 

Modify data frame accoring to mapping
Usage
mutate_mapping(data, mapping)
 #### Arguments 

data A data frame object.
mapping A mapping from hcaes function.
Examples
mutate_mapping(data = head(mtcars), mapping = hcaes(x = cyl, y = wt + cyl, group = gear))

