Transformations
Transformations are not really a part of ggplot2, but rather the scales package. Nevertheless it is an integral part of working with ggplot2 through its use in manipulating scales. ggforce expands the use of transformations to also include coordinate transformations.
Univariate transformations
This section describes the new transformations offered by ggforce for manipulating scales. In general the scales package has you well covered but there are some missing pieces:
Power transformations
Suspicously missing from the scales package is a generalized power transformation that is, e.g. x2. This type of transformation is only represented by the square root transformation which equals x1/2. ggforce provides a constructor for power transformations that can be used on scales etc.
p3 <- power_trans(3)
p3
## Transformer:  power of 3
p3$transform(1:5)
## [1]   1   8  27  64 125
ggplot(mtcars) + geom_point(aes(mpg, cyl)) + scale_y_continuous(trans = p3)

Reversing transformations
Scales provide reverse_trans() to create a reverse linear transformation. Unfortunatly you’re out of luck if you want a reverse log transformation etc. ggforce provides a transformation modifier that can reverse any transformation object passed into it:
p3r <- trans_reverser(p3)
p3r
## Transformer:  reverse-power of 3
ggplot(mtcars) + geom_point(aes(mpg, cyl)) + scale_y_continuous(trans = p3r)

Coordinate transformations
Coordinate transformation takes coordinates and does something to them. It can be simple rotations, shearing and reflections as you know from different image processing applications, or translating between different ways of representing data, e.g. radial to cartesian transformations. These types of transformations are closely linked to applying different coordinate systems to your plot, e.g. using coord polar, but can be applied to your data upfront instead of on the whole plot.
Radial transformations
radial_trans() converts radi and angle to x and y positions in a cartesian coordinate system. That means that if you have a point defined by its position on a circle you can easily get the x and y coordinates for it. The angle doesn’t need to be provided in radians or degrees as both the angular range and the radius range are defined when the transformation object is created. On top of that it can be defined where 0 starts (defaults to 12 o’clock) and which direction is used among others - see the documentation for radial_trans for a more in-depth description
line <- data.frame(
    x = seq(0, 10, length.out = 100), 
    y = seq(0, 10, length.out = 100)
)
r_trans <- radial_trans(r.range = c(0, 1), a.range = c(0, 2))
spiral <- r_trans$transform(r = line$x, a = line$y)
ggplot() + geom_path(aes(x, y), data = line, colour = 'red') + 
    geom_path(aes(x, y), data = spiral, colour = 'green')

#### Scales
Currently only a single new scale is added to ggplot2 with ggforce, but it is a rather nifty little fellow.
Units
Often, when working with numeric data, there’s a unit attached to the values, but in R this unit is not attached to your data but rather lives in your head. The developers of the units package has done something about this with the units class, which carries unit information around with a numeric vector. It provides more than semantics though. If you assign a new unit to the data it will check whether the new unit is compatible with the old one. If it is the values gets converted automatically, and if not an error is thrown. Furthermore, units also gets updated when making calculations with the values so units gets compounded during multiplication etc. Without ggforce units data would simply get converted to a numeric vector and work as normal. The scale_[x|y]_unit() scale from ggforce adds a couple of niceties though. When ggforce is loaded the scale is picked by default when plotting units data and you get all of the benefits for free.
The unit scale adds the unit to the axis label making it clear what the values on the axis is meassured in:
library(units)
## udunits system database from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/units/share/udunits
miles <- make_unit('miles')
## Warning: make_unit() is deprecated. Please use as_units()
gallon <- make_unit('gallon')
## Warning: make_unit() is deprecated. Please use as_units()
horsepower <- make_unit('horsepower')
## Warning: make_unit() is deprecated. Please use as_units()
mtcars$consumption <- mtcars$mpg * (miles/gallon)
mtcars$power <- mtcars$hp * horsepower

ggplot(mtcars) +
    geom_point(aes(power, consumption))

If data is transformed as part of an aesthetic assignment the unit will update automatically:
ggplot(mtcars) +
    geom_point(aes(power, 1/consumption))

Lastly it is possible to change the units used for the axes on the fly without touching the underlying data through the unit argument in the scale constructor. When doing this the data is automatically converted to the new unit.
ggplot(mtcars) +
    geom_point(aes(power, consumption)) +
    scale_x_unit(unit = 'W') +
    scale_y_unit(unit = 'km/l')
## Warning: make_unit() is deprecated. Please use as_units()

## Warning: make_unit() is deprecated. Please use as_units()

A rocket
We’ll finish this of by drawing a rocket:
rocketData <- data.frame(
  x = c(1,1,2,2),
  y = c(1,2,2,3)
)
rocketData <- do.call(rbind, lapply(seq_len(500)-1, function(i) {
  rocketData$y <- rocketData$y - c(0,i/500);
  rocketData$group <- i+1;
  rocketData
}))
rocketData2 <- data.frame(
  x = c(2, 2.25, 2),
  y = c(2, 2.5, 3)
)
rocketData2 <- do.call(rbind, lapply(seq_len(500)-1, function(i) {
  rocketData2$x[2] <- rocketData2$x[2] - i*0.25/500;
  rocketData2$group <- i+1 + 500;
  rocketData2
}))
ggplot() + geom_link(aes(x=2, y=2, xend=3, yend=3, alpha=..index..,
                     size = ..index..), colour='goldenrod', n=500) +
           geom_bezier(aes(x=x, y=y, group=group, colour=..index..),
                       data=rocketData) +
           geom_bezier(aes(x=y, y=x, group=group, colour=..index..),
                       data=rocketData) +
           geom_bezier(aes(x=x, y=y, group=group, colour=1),
                       data=rocketData2) +
           geom_bezier(aes(x=y, y=x, group=group, colour=1),
                       data=rocketData2) +
           geom_text(aes(x=1.65, y=1.65, label='ggplot2', angle=45),
                     colour='white', size=15) +
           coord_fixed() +
           scale_x_reverse() +
           scale_y_reverse() +
           scale_alpha(range=c(1, 0), guide='none') +
           scale_size_continuous(range=c(20, 0.1), trans='exp',
                                 guide='none') +
           scale_color_continuous(guide='none') +
           xlab('') + ylab('') +
           ggtitle('ggforce: Accelerating ggplot2') +
           theme(plot.title = element_text(size = 20))

Session info
## Session info -------------------------------------------------------------
##  setting  value                       
##  version  R version 3.5.0 (2018-04-23)
##  system   x86_64, darwin15.6.0        
##  ui       X11                         
##  language (EN)                        
##  collate  C                           
##  tz       Europe/Copenhagen           
##  date     2018-07-07
## Packages -----------------------------------------------------------------
##  package    * version    date       source                           
##  assertthat   0.2.0      2017-04-11 CRAN (R 3.5.0)                   
##  backports    1.1.2      2017-12-13 CRAN (R 3.5.0)                   
##  base       * 3.5.0      2018-04-24 local                            
##  bindr        0.1.1      2018-03-13 CRAN (R 3.5.0)                   
##  bindrcpp     0.2.2      2018-03-29 CRAN (R 3.5.0)                   
##  colorspace   1.3-2      2016-12-14 CRAN (R 3.5.0)                   
##  compiler     3.5.0      2018-04-24 local                            
##  datasets   * 3.5.0      2018-04-24 local                            
##  devtools     1.13.5     2018-02-18 CRAN (R 3.5.0)                   
##  digest       0.6.15     2018-01-28 CRAN (R 3.5.0)                   
##  dplyr        0.7.5      2018-05-19 CRAN (R 3.5.0)                   
##  evaluate     0.10.1     2017-06-24 CRAN (R 3.5.0)                   
##  farver       1.0        2018-06-28 Github (thomasp85/farver@d29b48c)
##  ggforce    * 0.1.3      2018-07-07 local                            
##  ggplot2    * 3.0.0      2018-07-03 CRAN (R 3.5.0)                   
##  glue         1.2.0      2017-10-29 CRAN (R 3.5.0)                   
##  graphics   * 3.5.0      2018-04-24 local                            
##  grDevices  * 3.5.0      2018-04-24 local                            
##  grid         3.5.0      2018-04-24 local                            
##  gtable       0.2.0      2016-02-26 CRAN (R 3.5.0)                   
##  htmltools    0.3.6      2017-04-28 CRAN (R 3.5.0)                   
##  knitr        1.20       2018-02-20 CRAN (R 3.5.0)                   
##  labeling     0.3        2014-08-23 CRAN (R 3.5.0)                   
##  lazyeval     0.2.1      2017-10-29 CRAN (R 3.5.0)                   
##  magrittr     1.5        2014-11-22 CRAN (R 3.5.0)                   
##  MASS         7.3-49     2018-02-23 CRAN (R 3.5.0)                   
##  memoise      1.1.0      2017-04-21 CRAN (R 3.5.0)                   
##  methods    * 3.5.0      2018-04-24 local                            
##  munsell      0.5.0      2018-06-12 CRAN (R 3.5.0)                   
##  pillar       1.2.3      2018-05-25 CRAN (R 3.5.0)                   
##  pkgconfig    2.0.1      2017-03-21 CRAN (R 3.5.0)                   
##  plyr         1.8.4      2016-06-08 CRAN (R 3.5.0)                   
##  purrr        0.2.5      2018-05-29 CRAN (R 3.5.0)                   
##  R6           2.2.2      2017-06-17 CRAN (R 3.5.0)                   
##  Rcpp         0.12.17    2018-05-18 CRAN (R 3.5.0)                   
##  reshape2     1.4.3      2017-12-11 CRAN (R 3.5.0)                   
##  rlang        0.2.1      2018-05-30 CRAN (R 3.5.0)                   
##  rmarkdown    1.10       2018-06-11 CRAN (R 3.5.0)                   
##  rprojroot    1.3-2      2018-01-03 CRAN (R 3.5.0)                   
##  scales       0.5.0      2017-08-24 CRAN (R 3.5.0)                   
##  stats      * 3.5.0      2018-04-24 local                            
##  stringi      1.2.3      2018-06-12 CRAN (R 3.5.0)                   
##  stringr      1.3.1      2018-05-10 CRAN (R 3.5.0)                   
##  tibble       1.4.2      2018-01-22 CRAN (R 3.5.0)                   
##  tidyselect   0.2.4      2018-02-26 CRAN (R 3.5.0)                   
##  tools        3.5.0      2018-04-24 local                            
##  tweenr       0.1.5.9999 2018-06-28 Github (thomasp85/tweenr@4d4f8d1)
##  units      * 0.6-0      2018-06-09 CRAN (R 3.5.0)                   
##  utils      * 3.5.0      2018-04-24 local                            
##  withr        2.1.2      2018-03-15 CRAN (R 3.5.0)                   
##  yaml         2.1.19     2018-05-01 CRAN (R 3.5.0)
