Post process for fortify. Based on ggplot2::qplot

#### Description 
 
Post process for fortify. Based on ggplot2::qplot

#### Usage 
 <pre><code>
post_autoplot(p, xlim = c(NA, NA), ylim = c(NA, NA), log = "",
main = NULL, xlab = NULL, ylab = NULL, asp = NULL)

#### Arguments 
 
p ggplot2::ggplot instances
xlim limits for x axis
ylim limits for y axis
log which variables to log transform ("x", "y", or "xy")
main character vector or expression for plot title
xlab character vector or expression for x axis label
ylab character vector or expression for y axis label
asp the y/x aspect ratio
Value
data.frame

#### Examples 

p <- qplot(Petal.Length, Petal.Width, data = iris)
ggfortify:::post_autoplot(p, xlim = c(1, 5), ylim = c(1, 5), log = 'xy', main = 'title',
xlab = 'x', ylab = 'y', asp = 1.5)
post_fortify
Post process for fortify.

#### Description 
 
Post process for fortify.

#### Usage 
 <pre><code>
post_fortify(data, klass = NULL)print,ggmultiplot-method
73

#### Arguments 
 
data
klass
data.frame
instance to be added as base_class attr, should be original model before fortified
Value
data.frame
print,ggmultiplot-method
Generic print function for ggmultiplot

#### Description 
 
Generic print function for ggmultiplot

#### Usage 
 <pre><code>
## S4 method for signature 'ggmultiplot'
print(x)

#### Arguments 
 
x
rbind_ts
ggmultiplot
Rbind original and predicted time-series-like instances as fortified
data.frame

#### Description 
 
Rbind original and predicted time-series-like instances as fortified data.frame

#### Usage 
 <pre><code>
rbind_ts(data, original, ts.connect = TRUE, index.name = "Index",
data.name = "Data")

#### Arguments 
 
data
original
ts.connect
index.name
data.name
Predicted/forecasted ts instance
Original ts instance
Logical frag indicates whether connects original time-series and predicted val-
ues
Specify column name for time series index
Specify column name for univariate time series data. Ignored in multivariate
time series.74
show,ggmultiplot-method
Value
data.frame

#### Examples 

predicted <- predict(stats::HoltWinters(UKgas), n.ahead = 5, prediction.interval = TRUE)
rbind_ts(predicted, UKgas, ts.connect = TRUE)
residuals.ar
Calcurate residuals for stats::ar

#### Description 
 
Calcurate residuals for stats::ar

#### Usage 
 <pre><code>
## S3 method for class 'ar'
residuals(object, ...)

#### Arguments 
 
object stats::ar instance
... other keywords
Value
ts Residuals extracted from the object object.

#### Examples 

residuals(ar(WWW
#### Usage 
 <pre><code>))
show,ggmultiplot-method
Generic show function for ggmultiplot

#### Description 
 
Generic show function for ggmultiplot

#### Usage 
 <pre><code>
## S4 method for signature 'ggmultiplot'
show(object)support_autoplot
75

#### Arguments 
 
object
ggmultiplot
support_autoplot
Check if passed object is supported by ggplot2::autoplot

#### Description 
 
Check if passed object is supported by ggplot2::autoplot

#### Usage 
 <pre><code>
support_autoplot(obj)

#### Arguments 
 
obj
object
Value
logical
unscale
Backtransform scale-ed object

#### Description 
 
Backtransform scale-ed object

#### Usage 
 <pre><code>
unscale(data, center = NULL, scale = NULL)

#### Arguments 
 
data
center
scale
Scaled data
Centered vector
Scale vector
Value
data.frame

#### Examples 

df <- iris[-5]
ggfortify::unscale(base::scale(df))
