
autoplot.pca_common
Autoplot PCA-likes

#### Description 
 
Autoplot PCA-likes

#### Usage 
 <pre><code>
## S3 method for class 'pca_common'
autoplot(object, data = NULL, scale = 1, x = 1,
y = 2, variance_percentage = TRUE, ...)

#### Arguments 
 
object PCA-like instance
data Joined to fitting result if provided.
scale scaling parameter, disabled by 0
x principal component number used in x axis
y
principal component number used in y axis
variance_percentage
show the variance explained by the principal component?
...
other 
#### Arguments 
  passed to [ggbiplot()]

#### Examples 

autoplot(stats::prcomp(iris[-5]))
autoplot(stats::prcomp(iris[-5]), data = iris)
autoplot(stats::prcomp(iris[-5]), data = iris, colour = 'Species')
autoplot(stats::prcomp(iris[-5]), label = TRUE, loadings = TRUE, loadings.label = TRUE)
autoplot(stats::prcomp(iris[-5]), frame = TRUE)
autoplot(stats::prcomp(iris[-5]), data = iris, frame = TRUE,
frame.colour = 'Species')
autoplot(stats::prcomp(iris[-5]), data = iris, frame = TRUE,
frame.type = 't', frame.colour = 'Species')24
autoplot.performance
autoplot(stats::princomp(iris[-5]))
autoplot(stats::princomp(iris[-5]), data = iris)
autoplot(stats::princomp(iris[-5]), data = iris, colour = 'Species')
autoplot(stats::princomp(iris[-5]), label = TRUE, loadings = TRUE, loadings.label = TRUE)
#Plot PC 2 and 3
autoplot(stats::princomp(iris[-5]), x = 2, y = 3)
#Don't show the variance explained
autoplot(stats::princomp(iris[-5]), variance_percentage = FALSE)
d.factanal <- stats::factanal(state.x77, factors = 3, scores = 'regression')
autoplot(d.factanal)
autoplot(d.factanal, data = state.x77, colour = 'Income')
autoplot(d.factanal, label = TRUE, loadings = TRUE, loadings.label = TRUE)
autoplot.performance
Autoplot ROCR::performance

#### Description 
 
Autoplot ROCR::performance

#### Usage 
 <pre><code>
## S3 method for class 'performance'
autoplot(object, p = NULL, bins = 5, ...)

#### Arguments 
 
object ROCR::performance instance
p ggplot2::ggplot instances
bins If object represents a measure whose value is just a scalar (e.g. performance(predObj, 'auc')),
a histogram will be plotted of this scalar’s values for different runs. bins is the
number of bins for this histogram.
... other 
#### Arguments 
  passed to methods
Value
ggplotautoplot.RasterCommon
autoplot.RasterCommon Autoplot raster::raster

#### Description 
 
Only plot the first layer of the given raster

#### Usage 
 <pre><code>
## S3 method for class 'RasterCommon'
autoplot(object, raster.layer = NULL, p = NULL,
alpha = NULL, xlim = c(NA, NA), ylim = c(NA, NA), log = "",
main = NULL, xlab = "", ylab = "", asp = NULL, ...)

#### Arguments 
 
object raster::raster instance
raster.layer name of the layer to plot
p ggplot2::ggplot instance
alpha alpha
xlim limits for x axis
ylim limits for y axis
log which variables to log transform ("x", "y", or "xy")
main character vector or expression for plot title
xlab character vector or expression for x axis label
ylab character vector or expression for y axis label
asp the y/x aspect ratio
... other 
#### Arguments 
  passed to methods
Value
ggplot
2526
autoplot.SpatialCommon
autoplot.SpatialCommon
Autoplot maps::map

#### Description 
 
Autoplot maps::map

#### Usage 
 <pre><code>
## S3 method for class 'SpatialCommon'
autoplot(object, p = NULL, group = NULL,
colour = "black", size = NULL, linetype = NULL, alpha = NULL,
fill = NULL, shape = NULL, xlim = c(NA, NA), ylim = c(NA, NA),
log = "", main = NULL, xlab = "", ylab = "", asp = NULL, ...)

#### Arguments 
 
object maps::map instance
p ggplot2::ggplot instance
group key for grouping geoms
colour line colour
size point size
linetype line type
alpha alpha
fill fill colour
shape point shape
xlim limits for x axis
ylim limits for y axis
log which variables to log transform ("x", "y", or "xy")
main character vector or expression for plot title
xlab character vector or expression for x axis label
ylab character vector or expression for y axis label
asp the y/x aspect ratio
... other 
#### Arguments 
  passed to methods
Value
ggplotautoplot.spec
27
autoplot.spec
Autoplot stats::spec

#### Description 
 
Autoplot stats::spec

#### Usage 
 <pre><code>
## S3 method for class 'spec'
autoplot(object, xlim = c(NA, NA), ylim = c(NA, NA),
log = "y", main = NULL, xlab = NULL, ylab = NULL, asp = NULL, ...)

#### Arguments 
 
object stats::spec instance
xlim limits for x axis
ylim limits for y axis
log which variables to log transform ("x", "y", or "xy")
main character vector or expression for plot title
xlab character vector or expression for x axis label
ylab character vector or expression for y axis label
asp the y/x aspect ratio
... other 
#### Arguments 
  passed to methods
Value
ggplot

#### Examples 

autoplot(stats::spec.ar(AirPassengers))
autoplot(stats::spec.pgram(AirPassengers))
