autoplot.stepfun
Plot stats::stepfun

#### Description 
 
Plot stats::stepfun

#### Usage 
 <pre><code>
## S3 method for class 'stepfun'
autoplot(object, colour = NULL, size = NULL,
linetype = NULL, alpha = NULL, shape = 1, xlim = c(NA, NA),
ylim = c(NA, NA), log = "", main = NULL, xlab = NULL, ylab = NULL,
asp = NULL, ...)

#### Arguments 
 
object stats::stepfun instance
colour colour
size point size
linetype line type
alpha alpha
shape point shape
xlim limits for x axis
ylim limits for y axis
log which variables to log transform ("x", "y", or "xy")
main character vector or expression for plot title
xlab character vector or expression for x axis label
ylab character vector or expression for y axis label
asp the y/x aspect ratio
... other 
#### Arguments 
  passed to methods
Value
ggplot

#### Examples 

autoplot(stepfun(c(1, 2, 3), c(4, 5, 6, 7)))
autoplot(stepfun(c(1), c(4, 5)), shape = NULL)
autoplot(stepfun(c(1, 3, 4, 8), c(4, 5, 2, 3, 5)), linetype = 'dashed')
autoplot(stepfun(c(1, 2, 3, 4, 5, 6, 7, 8, 10), c(4, 5, 6, 7, 8, 9, 10, 11, 12, 9)), colour = 'red')autoplot.survfit
autoplot.survfit
29
Autoplot survival::survfit

#### Description 
 
Autoplot survival::survfit

#### Usage 
 <pre><code>
## S3 method for class 'survfit'
autoplot(object, fun = NULL, surv.geom = "step",
surv.colour = NULL, surv.size = NULL, surv.linetype = NULL,
surv.alpha = NULL, surv.fill = NULL, surv.shape = NULL,
surv.connect = TRUE, conf.int = TRUE, conf.int.colour = "#0000FF",
conf.int.linetype = "none", conf.int.fill = "#000000",
conf.int.alpha = 0.3, censor = TRUE, censor.colour = NULL,
censor.size = 3, censor.alpha = NULL, censor.shape = "+",
facets = FALSE, nrow = NULL, ncol = 1, grid = FALSE,
strip_swap = FALSE, scales = "free_y", xlim = c(NA, NA), ylim = c(NA,
NA), log = "", main = NULL, xlab = NULL, ylab = NULL, asp = NULL,
...)

#### Arguments 
 
object survival::survfit instance
fun an arbitrary function defining a transformation of the survival curve
surv.geom geometric string for survival curve. ’step’, ’line’ or ’point’
surv.colour line colour for survival curve
surv.size point size for survival curve
surv.linetype line type for survival curve
surv.alpha alpha for survival curve
surv.fill fill colour survival curve
surv.shape point shape survival curve
surv.connect logical frag indicates whether connects survival curve to the origin
conf.int
Logical flag indicating whether to plot confidence intervals
conf.int.colour
line colour for confidence intervals
conf.int.linetype
line type for confidence intervals
conf.int.fill
fill colour for confidence intervals
conf.int.alpha alpha for confidence intervals
censor
Logical flag indicating whether to plot censors30
autoplot.ts
censor.colour colour for censors
censor.size size for censors
censor.alpha alpha for censors
censor.shape shape for censors
facets Logical value to specify use facets
nrow Number of facet/subplot rows
ncol Number of facet/subplot columns
grid Logical flag indicating whether to draw grid
strip_swap swap facet or grid strips
scales Scale value passed to ggplot2
xlim limits for x axis
ylim limits for y axis
log which variables to log transform ("x", "y", or "xy")
main character vector or expression for plot title
xlab character vector or expression for x axis label
ylab character vector or expression for y axis label
asp the y/x aspect ratio
... other 
#### Arguments 
  passed to methods
Value
ggplot

#### Examples 

library(survival)
autoplot(survfit(Surv(time, status) ~ sex, data = lung))
autoplot(survfit(Surv(time, status) ~ sex, data = lung), facets = TRUE)
autoplot(survfit(Surv(time, status) ~ 1, data = lung))
autoplot(survfit(Surv(time, status) ~ sex, data=lung), conf.int = FALSE, censor = FALSE)
autoplot(survfit(coxph(Surv(time, status) ~ sex, data = lung)))
autoplot.ts

#### Description 
 
Autoplot time-series-like
Autoplot time-series-likeautoplot.ts
31

#### Usage 
 <pre><code>
## S3 method for class 'ts'
autoplot(object, columns = NULL, group = NULL,
is.date = NULL, index.name = "Index", p = NULL, ts.scale = FALSE,
stacked = FALSE, facets = TRUE, nrow = NULL, ncol = 1,
scales = "free_y", ts.geom = "line", ts.colour = NULL, ts.size = NULL,
ts.linetype = NULL, ts.alpha = NULL, ts.fill = NULL, ts.shape = NULL,
geom = ts.geom, colour = ts.colour, size = ts.size,
linetype = ts.linetype, alpha = ts.alpha, fill = ts.fill,
shape = ts.shape, xlim = c(NA, NA), ylim = c(NA, NA), log = "",
main = NULL, xlab = "", ylab = "", asp = NULL, ...)

#### Arguments 
 
object time-series-like instance
columns Character vector specifies target column name(s)
group Character vector specifies grouping
is.date Logical frag indicates whether the stats::ts is date or not If not provided,
regard the input as date when the frequency is 4 or 12
index.name Specify column name for time series index when passing data.frame via data.
p ggplot2::ggplot instance
ts.scale Logical flag indicating whether to perform scaling each timeseries
stacked Logical flag indicating whether to stack multivariate timeseries
facets Logical value to specify use facets
nrow Number of facet/subplot rows
ncol Number of facet/subplot columns
scales Scale value passed to ggplot2
ts.geom geometric string for time-series. ’line’, ’bar’, ’ribbon’, or ’point’
ts.colour line colour for time-series
ts.size point size for time-series
ts.linetype line type for time-series
ts.alpha alpha for time-series
ts.fill fill colour for time-series
ts.shape point shape for time-series
geom same as ts.geom
colour same as ts.colour
size same as ts.size
linetype same as ts.linetype
alpha same as ts.alpha
fill same as ts.fill32
autoplot.tsmodel
shape same as ts.shape
xlim limits for x axis
ylim limits for y axis
log which variables to log transform ("x", "y", or "xy")
main character vector or expression for plot title
xlab character vector or expression for x axis label
ylab character vector or expression for y axis label
asp the y/x aspect ratio
... other 
#### Arguments 
  passed to methods
Value
ggplot

#### Examples 

## Not run:
data(Canada, package = 'vars')
autoplot(AirPassengers)
autoplot(UKgas, ts.geom = 'bar')
autoplot(Canada)
autoplot(Canada, facets = FALSE)
library(zoo)
autoplot(xts::as.xts(AirPassengers))
autoplot(timeSeries::as.timeSeries(AirPassengers))
its <- tseries::irts(cumsum(rexp(10, rate = 0.1)), matrix(rnorm(20), ncol=2))
autoplot(its)
autoplot(stats::stl(UKgas, s.window = 'periodic'))
autoplot(stats::decompose(UKgas))
## End(Not run)
autoplot.tsmodel
Autoplot time series models (like AR, ARIMA)

#### Description 
 
Autoplot time series models (like AR, ARIMA)autoplot.tsmodel
33

#### Usage 
 <pre><code>
## S3 method for class 'tsmodel'
autoplot(object, data = NULL, predict = NULL,
is.date = NULL, ts.connect = TRUE, fitted.geom = "line",
fitted.colour = "#FF0000", fitted.size = NULL, fitted.linetype = NULL,
fitted.alpha = NULL, fitted.fill = NULL, fitted.shape = NULL,
predict.geom = "line", predict.colour = "#0000FF", predict.size = NULL,
predict.linetype = NULL, predict.alpha = NULL, predict.fill = NULL,
predict.shape = NULL, conf.int = TRUE, conf.int.colour = "#0000FF",
conf.int.linetype = "none", conf.int.fill = "#000000",
conf.int.alpha = 0.3, ...)

#### Arguments 
 
object Time series model instance
data original dataset, needed for stats::ar, stats::Arima
predict Predicted stats::ts If not provided, try to retrieve from current environment
using variable name.
is.date Logical frag indicates whether the stats::ts is date or not. If not provided,
regard the input as date when the frequency is 4 or 12
ts.connect Logical frag indicates whether connects original time-series and predicted val-
ues
fitted.geom geometric string for fitted time-series
fitted.colour line colour for fitted time-series
fitted.size
point size for fitted time-series
fitted.linetype
line type for fitted time-series
fitted.alpha alpha for fitted time-series
fitted.fill fill colour for fitted time-series
fitted.shape point shape for fitted time-series
predict.geom geometric string for predicted time-series
predict.colour line colour for predicted time-series
predict.size
point size for predicted time-series
predict.linetype
line type for predicted time-series
predict.alpha alpha for predicted time-series
predict.fill fill colour for predicted time-series
predict.shape point shape for predicted time-series
conf.int
Logical flag indicating whether to plot confidence intervals
conf.int.colour
line colour for confidence intervals
conf.int.linetype
line type for confidence intervals34
autoplot.varprd
conf.int.fill
fill colour for confidence intervals
conf.int.alpha alpha for confidence intervals
...
Keywords passed to autoplot.ts
Value
ggplot

#### Examples 

d.ar <- stats::ar(AirPassengers)
autoplot(d.ar)
autoplot(d.ar, predict = predict(d.ar, n.ahead = 5))
autoplot(stats::arima(UKgas), data = UKgas)
autoplot(forecast::arfima(AirPassengers))
autoplot(forecast::nnetar(UKgas), is.date = FALSE)
d.holt <- stats::HoltWinters(USAccDeaths)
autoplot(d.holt)
autoplot(d.holt, predict = predict(d.holt, n.ahead = 5))
autoplot(d.holt, predict = predict(d.holt, n.ahead = 5, prediction.interval = TRUE))
