
plot.gg_error Plot a gg_error object
#### Description 

A plot of the cumulative OOB error rates of the random forest as a function of number of trees.
#### Usage 
<pre><code>

## S3 method for class 'gg_error'
plot(x, ...)

</code></pre>
#### Arguments

* x gg_error object created from a rfsrc object
* ... extra arguments passed to ggplot functions


#### Examples 
```{r} 

## Not run:
## #### Examples from RFSRC package...
## ------------------------------------------------------------
## classification example
## ------------------------------------------------------------
## ------------- iris data
## You can build a randomForest
# rfsrc_iris <- rfsrc(Species ~ ., data = iris)
# ... or load a cached randomForestSRC object
data(rfsrc_iris, package="ggRandomForests")
# Get a data.frame containing error rates
gg_dta<- gg_error(rfsrc_iris)
# Plot the gg_error object
plot(gg_dta)
## ------------------------------------------------------------
## Regression example
## ------------------------------------------------------------
## ------------- airq data
# rfsrc_airq <- rfsrc(Ozone ~ ., data = airquality, na.action = "na.impute")
# ... or load a cached randomForestSRC object
data(rfsrc_airq, package="ggRandomForests")
# Get a data.frame containing error rates
gg_dta<- gg_error(rfsrc_airq)
# Plot the gg_error object
plot(gg_dta)
38 plot.gg_interaction
## ------------- Boston data
data(rfsrc_Boston, package="ggRandomForests")
# Get a data.frame containing error rates
gg_dta<- gg_error(rfsrc_Boston)
# Plot the gg_error object
plot(gg_dta)
## ------------- mtcars data
data(rfsrc_mtcars, package="ggRandomForests")
# Get a data.frame containing error rates
gg_dta<- gg_error(rfsrc_mtcars)
# Plot the gg_error object
plot(gg_dta)
## ------------------------------------------------------------
## Survival example
## ------------------------------------------------------------
## ------------- veteran data
## randomized trial of two treatment regimens for lung cancer
# data(veteran, package = "randomForestSRC")
# rfsrc_veteran <- rfsrc(Surv(time, status) ~ ., data = veteran, ntree = 100)
# Load a cached randomForestSRC object
data(rfsrc_veteran, package="ggRandomForests")
gg_dta <- gg_error(rfsrc_veteran)
plot(gg_dta)
## ------------- pbc data
# Load a cached randomForestSRC object
data(rfsrc_pbc, package="ggRandomForests")
gg_dta <- gg_error(rfsrc_pbc)
plot(gg_dta)
## End(Not run)


#### Details
The gg_error plot is used to track the convergence of the randomForest. This figure is a reproduction
of the error plot from the plot.rfsrc function.

#### Value
ggplot object

See Also
gg_error rfsrc plot.rfsrc
